image: ubuntu:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEBIAN_FRONTEND: noninteractive
  GIT_SUBMODULE_STRATEGY: recursive
  
# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update
  - apt-get install -y build-essential cmake ninja-build 

#sca:
#  script:
#    - pip3 install black
#    - black .

test:
  script:
    - mkdir build 
    - cd build 
    - cmake ..
    - cmake --build . 
    - export PYTHONPATH=${PWD}/../python/
    - py.test ../test
