
name: docs-bot
on:
  status
jobs:
  run-docs-bot:
    if: ${{ github.repository == 'apache/tvm' && github.event.state == 'success' && github.event.context == 'tvm-ci/pr-head' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Comment link to docs
        env:
          COMMIT_SHA: ${{ github.event.sha }}
          TARGET_URL: ${{ github.event.target_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          python tests/scripts/github_docs_comment.py