
name: Nightly Docker Update
on:
  workflow_dispatch:

concurrency:
  group: nightly-docker-update
  cancel-in-progress: true

jobs:
  open_update_pr:
    permissions:
      actions: write
      checks: write
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      statuses: write
    if: github.repository == 'apache/tvm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Open PR to update Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eux
          python ci/scripts/jenkins/open_docker_update_pr.py
